### ISSUE TITLE
Research on how to tag the articles for filter and search purpose

### ISSUE THREAD

**Issue by michelleli94** [diamondinrough/app#10]
- How to tag so that it is more efficient and extensible

**Comment by zhangqi444** [comment]
http://stackoverflow.com/questions/3267609/mysql-join-query-for-multiple-tags-many-to-many-relationship-that-matches-al

This example shows how to do multiple tags based filter search.
Basically it uses 3 tables to implement n to m relationship in MySQL which is a very general way.
To No-sql, MySQL needs more complexity script to implement the join select.
Let us use MySQL still.
