### ISSUE TITLE
Client side environment set up

### ISSUE THREAD

**Issue by zhangqi444** [diamondinrough/app#2]
- [ ] [IOS](https://developer.apple.com/)
- [ ] [PhoneGap](http://phonegap.com/)/[Cordova](http://cordova.apache.org/)
- [x] [ionic](http://ionicframework.com/)

Investigate how to set up the hybrid app development environment.
Here is a step by step example.
[Create a simple hybrid app with Angular JS, Ionic and Cordova](https://youtu.be/sCnGSOaaZFo)

**Comment by cihrsliu** [comment]
[Documentation](https://1drv.ms/o/s!Aur1Ho74X8tIgRRfpOIHi8mClKxl) under Development/Mobile Environment Setup
