### ISSUE TITLE
Server side development environment set up

### ISSUE THREAD

**Issue by zhangqi444** [diamondinrough/app#3]
- [x] [Django](https://www.djangoproject.com/) 
- [x] [Django rest framework](http://www.django-rest-framework.org/)
- [x] mysql
- [ ] [mezzanine](http://mezzanine.jupo.org/) 

Step by step example
[Django Web Development with Python](http://www.youtube.com/playlist?list=PLQVvvaa0QuDeA05ZouE4OzDYLHY-XH-Nd)

**Comment by cihrsliu** [comment]
[Documentation](https://1drv.ms/o/s!Aur1Ho74X8tIgRRfpOIHi8mClKxl) on OneDrive under Development/Environment Setup
