### ISSUE TITLE
AWS investigation and set up

### ISSUE THREAD

**Issue by zhangqi444** [diamondinrough/app#4]
- [x] [EC2](https://aws.amazon.com/ec2/?nc2=h_m1)
- [x] [DynamalDB](https://aws.amazon.com/dynamodb/?nc2=h_m1)
- [x] Account create and management

**Comment by cihrsliu** [comment]
[Documentation](https://1drv.ms/o/s!Aur1Ho74X8tIgRRfpOIHi8mClKxl) on OneDrive under Development/Environment Setup

**Comment by zhangqi444** [comment]
We use RDS instead of DynamolDB.
54.152.36.188:8100
