### ISSUE TITLE
Create basic server side package with django working

### ISSUE THREAD

**Issue by zhangqi444** [diamondinrough/app#6]
1. create our server side code base an update it to the github
2. create the document about how to deploy the code to server side
3. share out the server side endpoint to make it able to be connected from public network.

Please have document for all the related staff.

**Comment by cihrsliu** [comment]
created test django project with rest framework and basic app, running on aws [here](http://54.152.36.188/), uploaded django files to chris-djangotest branch

**Comment by zhangqi444** [comment]
Good job. If it is verified, go ahead to push it to mainline.
